package com.map.locationpicker

object Constants {
  const val INITIAL_LATITUDE_INTENT = "INITIAL_LATITUDE_INTENT"
  const val INITIAL_LONGITUDE_INTENT = "INITIAL_LONGITUDE_INTENT"
  const val INITIAL_ZOOM_INTENT = "INITIAL_ZOOM_INTENT"
  const val MARKER_COLOR_RES_INTENT = "MARKER_COLOR_RES_INTENT"
  const val FAB_COLOR_RES_INTENT = "FAB_COLOR_RES_INTENT"
  const val PRIMARY_TEXT_COLOR_RES_INTENT = "PRIMARY_TEXT_COLOR_RES_INTENT"
  const val BOTTOM_VIEW_COLOR_RES_INTENT = "BOTTOM_VIEW_COLOR_RES_INTENT"
  const val MAP_RAW_STYLE_RES_INTENT = "MAP_RAW_STYLE_RES_INTENT"
  const val MAP_TYPE_INTENT: String="MAP_TYPE_INTENT"
  const val DEFAULT_LATITUDE = 40.748672
  const val DEFAULT_LONGITUDE = -73.985628
  const val DEFAULT_ZOOM = 14.0F
  const val PLACE_PICKER_REQUEST = 100
  const val DEFAULT_SLIDER_VALUE_FROM_INTENT = 1.0F
  const val DEFAULT_SLIDER_VALUE_TO_INTENT = 200.0F
  const val DEFAULT_CIRCLE_RADIUS_INTENT = 5.0
  const val CIRCLE_INTENT = "CIRCLE_INTENT"
  const val GOOGLE_API_KEY = "GOOGLE_API_KEY"
  const val HIDE_LOCATION_BUTTON = "HIDE_LOCATION"
  const val SLIDER_THUMB_COLOR_RES_INTENT = "SLIDER_THUMB_COLOR_RES_INTENT"
  const val SLIDER_TRACK_ACTIVE_COLOR_RES_INTENT = "SLIDER_TRACK_ACTIVE_COLOR_RES_INTENT"
  const val SLIDER_TRACK_INACTIVE_COLOR_RES_INTENT = "SLIDER_TRACK_INACTIVE_COLOR_RES_INTENT"
  const val INITIAL_SLIDER_VALUE_FROM_INTENT = "INITIAL_SLIDER_VALUE_FROM_INTENT"
  const val INITIAL_SLIDER_VALUE_TO_INTENT = "INITIAL_SLIDER_VALUE_TO_INTENT"
  const val INITIAL_CIRCLE_RADIUS_INTENT = "INITIAL_CIRCLE_RADIUS_INTENT"
}